version: '3.7'
services:

  organizationservice:
    image: orgserv:latest
    ports:
      - "8075:8075"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_CLOUD_CONFIG_URI:
        http://192.168.0.207:8071
    networks:
      backend:
        aliases:
          - orgserv
networks:
  backend:
    external:
      name: backendnetwork