version: '3.7'
services:

  organozationservice:
    image: orgserv:latest
    ports:
      - "8075:8075"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_CLOUD_CONFIG_URI:
        http://192.168.0.207:8071
    depends_on:
      - postgres
    networks:
      backend:
        aliases:
          - "orgserv"
networks:
  backend:
    driver: bridge